### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by WaruiAlfred** [WaruiAlfred/shell#1]
`main(12855,0x102964580) malloc: *** error for object 0x16d553430: pointer being realloc'd was not allocated
main(12855,0x102964580) malloc: *** set a breakpoint in malloc_error_break to debug`

the problem is here **getline** function look at it and give an alternative

**Comment by kahenyamercy** [comment]
Set lineptr pointer to NULL

**Comment by kahenyamercy** [comment]
fix by setting the line pointer to null
